name: Upload Stock Collector to EC2

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Archive repository into ./build folder (excluding .git and build)
        run: |
          mkdir -p build
          rsync -av --exclude='.git' --exclude='build' ./ ./build/

      - name: Upload to EC2 ~/infra/stock-collector/
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_CI_KEY }}
          source: "build/*"
          target: "~/infra/stock-collector"
